import { useEffect, useMemo, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Check, Palette, Plus, Trash2, X } from "lucide-react";
import type { CourseSlot, Item, ItemInput, Tag } from "@calendar/domain";
import { ApiError, apiJson } from "../lib/api";

const WEEKDAYS = [["周一", 1], ["周二", 2], ["周三", 3], ["周四", 4], ["周五", 5], ["周六", 6], ["周日", 0]] as const;
const COLORS = ["#f97316", "#3b82f6", "#22c55e", "#8b5cf6", "#ec4899", "#06b6d4", "#eab308", "#64748b"];
type Scope = "this" | "slot" | "all";
interface CourseEditorProps { open: boolean; item?: Item | null; occurrenceKey?: string | null; slotId?: string | null; defaults?: { startAt: string; endAt: string } | null; tags: Tag[]; onClose: () => void; onSaved: (item?: Item, deleted?: boolean) => void; }
function slotFromDefaults(defaults?: { startAt: string; endAt: string } | null): CourseSlot { const start = defaults ? new Date(defaults.startAt) : new Date(); const end = defaults ? new Date(defaults.endAt) : new Date(start.getTime() + 3600000); const pad = (value: number) => String(value).padStart(2, "0"); return { id: crypto.randomUUID(), weekday: start.getDay(), startTime: `${pad(start.getHours())}:${pad(start.getMinutes())}`, endTime: `${pad(end.getHours())}:${pad(end.getMinutes())}`, weekParity: "all" }; }
function slotDate(slot: CourseSlot, anchor?: string | null, fallback?: string | null): Date { const base = new Date(anchor ?? fallback ?? new Date()); const [hour, minute] = slot.startTime.split(":").map(Number); base.setHours(hour ?? 0, minute ?? 0, 0, 0); return base; }
function localDateInput(value?: string | null): string { if (!value) return ""; if (/^\d{4}-\d{2}-\d{2}$/.test(value)) return value; const date = new Date(value); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
function defaultCourseEndDate(startDate: string): string { if (!startDate) return ""; const date = new Date(`${startDate}T12:00:00`); if (Number.isNaN(date.getTime())) return ""; date.setDate(date.getDate() + 17 * 7); return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`; }
export function CourseEditor({ open, item, occurrenceKey, slotId, defaults, tags, onClose, onSaved }: CourseEditorProps) {
  const initialSlots = useMemo(() => item?.courseSlots?.length ? item.courseSlots : [slotFromDefaults(defaults)], [item, defaults]);
  const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [location, setLocation] = useState(""); const [priority, setPriority] = useState<Item["priority"]>("none"); const [tagIds, setTagIds] = useState<string[]>([]); const [color, setColor] = useState<string | null>(null); const [showInTimetable, setShowInTimetable] = useState(true); const [courseStartDate, setCourseStartDate] = useState(""); const [courseEndDate, setCourseEndDate] = useState(""); const [slots, setSlots] = useState<CourseSlot[]>([]); const [scope, setScope] = useState<Scope>("slot"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!open) return; setTitle(item?.title ?? ""); setDescription(item?.description ?? ""); setLocation(item?.location ?? ""); setPriority(item?.priority ?? "none"); setTagIds(item?.tagIds ?? []); setColor(item?.timetableColor ?? null); setShowInTimetable(item?.showInTimetable ?? true); const initialCourseStart = item?.courseStartDate ?? localDateInput(defaults?.startAt); setCourseStartDate(initialCourseStart); setCourseEndDate(item?.courseEndDate ?? defaultCourseEndDate(initialCourseStart)); setSlots(initialSlots); setScope(item ? "slot" : "all"); setError(""); }, [open, item, initialSlots]);
  function updateSlot(index: number, patch: Partial<CourseSlot>) { setSlots((current) => current.map((slot, position) => position === index ? { ...slot, ...patch } : slot)); }
  function removeSlot(index: number) { setSlots((current) => current.filter((_, position) => position !== index)); }
  function addSlot() { const last = slots[slots.length - 1]; setSlots((current) => [...current, { ...(last ?? slotFromDefaults(defaults)), id: crypto.randomUUID(), weekday: (last?.weekday ?? 1), startTime: last?.startTime ?? "08:00", endTime: last?.endTime ?? "08:45", weekParity: "all" }]); }
  function payload(overrideSlots = slots): ItemInput { const first = overrideSlots[0] ?? slotFromDefaults(defaults); const anchor = item?.startAt ?? defaults?.startAt ?? slotDate(first).toISOString(); return { kind: item?.kind === "both" ? "both" : "event", title: title.trim(), description, location, startAt: anchor, endAt: item?.endAt ?? defaults?.endAt ?? slotDate(first).toISOString(), dueAt: null, isAllDay: false, timezone: item?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone, priority, status: item?.status ?? "active", completedAt: item?.completedAt ?? null, autoRollover: item?.autoRollover ?? false, showInTimetable, timetableColor: color, courseStartDate: courseStartDate || null, courseEndDate: courseEndDate || null, courseSlots: overrideSlots, parentId: null, recurrence: null, tagIds, reminders: item?.reminders ?? [] }; }  async function save() { if (!title.trim()) { setError("请输入课程名称"); return; } if (slots.length === 0) { setError("至少保留一个每周时间段"); return; } if (courseStartDate && courseEndDate && courseEndDate < courseStartDate) { setError("结束日期不能早于开始日期"); return; } setBusy(true); setError(""); try { if (!item) { const response = await apiJson<{ item: Item }>("/api/v1/items", "POST", payload()); onSaved(response.item); onClose(); return; } if (scope === "this" && occurrenceKey) { await apiJson(`/api/v1/items/${item.id}/exceptions/${encodeURIComponent(occurrenceKey)}`, "PUT", { action: "override", override: payload(slots) }); onSaved(item); onClose(); return; } const nextSlots = scope === "slot" && slotId ? slots.map((slot) => slot.id === slotId ? slot : item.courseSlots.find((original) => original.id === slot.id) ?? slot) : slots; const response = await apiJson<{ item: Item }>(`/api/v1/items/${item.id}`, "PATCH", payload(nextSlots)); onSaved(response.item); onClose(); } catch (cause) { setError(cause instanceof ApiError ? cause.message : "保存失败"); } finally { setBusy(false); } }
  async function remove() { if (!item) return; if (scope === "this" && occurrenceKey) { await apiJson(`/api/v1/items/${item.id}/exceptions/${encodeURIComponent(occurrenceKey)}`, "PUT", { action: "cancelled" }); onSaved(item, false); onClose(); return; } if (scope === "slot" && slotId) { const result = await apiJson<{ deleted: boolean }>(`/api/v1/items/${item.id}/course-slots/${slotId}`, "DELETE"); onSaved(item, result.deleted); onClose(); return; } await apiJson(`/api/v1/items/${item.id}`, "DELETE"); onSaved(item, true); onClose(); }  return <Dialog.Root open={open} onOpenChange={(next) => !next && onClose()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-stone-950/50 backdrop-blur-sm"/><Dialog.Content className="fixed inset-x-0 bottom-0 z-50 max-h-[92vh] overflow-y-auto rounded-t-3xl border border-app bg-[var(--surface)] p-5 shadow-2xl sm:inset-x-4 sm:bottom-4 sm:mx-auto sm:max-w-3xl sm:rounded-3xl sm:p-6"><div className="flex items-start justify-between"><div><Dialog.Title className="text-xl font-black">{item ? "编辑课程" : "新建课程"}</Dialog.Title><Dialog.Description className="muted mt-1 text-sm">同一课程可以有多个每周时间段，内容默认共享</Dialog.Description></div><Dialog.Close className="grid size-10 place-items-center rounded-full hover-surface"><X size={18}/></Dialog.Close></div>
    <div className="mt-5 space-y-4"><label><span className="text-sm font-bold">课程名称</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="例如：高等数学" className="mt-1 w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5 font-bold"/></label><div className="grid gap-3 sm:grid-cols-2"><label><span className="text-sm font-bold">地点</span><input value={location} onChange={(event) => setLocation(event.target.value)} className="mt-1 w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5"/></label><label><span className="text-sm font-bold">优先级</span><select value={priority} onChange={(event) => setPriority(event.target.value as Item["priority"])} className="mt-1 w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5"><option value="none">无</option><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option></select></label></div><label><span className="text-sm font-bold">备注</span><textarea value={description} onChange={(event) => setDescription(event.target.value)} className="mt-1 min-h-24 w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5"/></label>
    <div><div className="flex items-center justify-between"><span className="text-sm font-bold">每周时间段</span><button onClick={addSlot} className="flex items-center gap-1 rounded-lg border border-app px-3 py-1.5 text-xs font-bold"><Plus size={14}/>添加时间段</button></div><div className="mt-2 space-y-2">{slots.map((slot, index) => <div key={slot.id} className="grid gap-2 rounded-2xl border border-app p-3 sm:grid-cols-[1fr_1fr_1fr_1fr_auto]"><select value={slot.weekday} onChange={(event) => updateSlot(index, { weekday: Number(event.target.value) })} className="rounded-xl border border-app bg-[var(--input-bg)] px-2 py-2 text-sm">{WEEKDAYS.map(([label, value]) => <option key={value} value={value}>{label}</option>)}</select><input type="time" value={slot.startTime} onChange={(event) => updateSlot(index, { startTime: event.target.value })} className="rounded-xl border border-app bg-[var(--input-bg)] px-2 py-2 text-sm"/><input type="time" value={slot.endTime} onChange={(event) => updateSlot(index, { endTime: event.target.value })} className="rounded-xl border border-app bg-[var(--input-bg)] px-2 py-2 text-sm"/><select value={slot.weekParity} onChange={(event) => updateSlot(index, { weekParity: event.target.value as CourseSlot["weekParity"] })} className="rounded-xl border border-app bg-[var(--input-bg)] px-2 py-2 text-sm"><option value="all">每周</option><option value="odd">单周</option><option value="even">双周</option></select><button onClick={() => removeSlot(index)} className="grid place-items-center rounded-lg border border-red-300 p-2 text-danger dark:border-red-900" title="删除时间段"><Trash2 size={15}/></button></div>)}</div></div><div className="mt-4 grid gap-3 sm:grid-cols-2">
      <label><span className="text-sm font-bold">开始日期</span><input type="date" value={courseStartDate} onChange={(event) => setCourseStartDate(event.target.value)} className="mt-1 w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5"/><span className="muted mt-1 block text-xs">默认使用课表中选中的日期；留空表示不限开始时间</span></label>
      <label><span className="text-sm font-bold">结束日期</span><input type="date" value={courseEndDate} onChange={(event) => setCourseEndDate(event.target.value)} className="mt-1 w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5"/><span className="muted mt-1 block text-xs">留空表示长期有效；结束日期当天仍会显示</span></label>
    </div>
    <label className="mt-4 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={showInTimetable} onChange={(event) => setShowInTimetable(event.target.checked)}/>显示在课程表</label><div className="mt-4"><div className="flex items-center gap-2 text-sm font-bold"><Palette size={16}/>课程颜色</div><div className="mt-2 flex flex-wrap items-center gap-2">{COLORS.map((value) => <button key={value} onClick={() => setColor(value)} className={`size-8 rounded-full border-2 ${color === value ? "border-stone-950 dark:border-white" : "border-transparent"}`} style={{ backgroundColor: value }} title={value}>{color === value && <Check className="mx-auto text-white" size={14}/>}</button>)}<input type="color" value={color ?? "#f97316"} onChange={(event) => setColor(event.target.value)} className="h-8 w-12 cursor-pointer rounded border border-app bg-transparent" title="自定义颜色"/><button onClick={() => setColor(null)} className="rounded-lg border border-app px-3 py-1 text-xs">自动</button></div></div>
    {item && <div className="mt-4"><p className="text-sm font-bold">修改范围</p><div className="mt-2 grid gap-2 sm:grid-cols-3">{[["this", "仅本次"], ["slot", "当前时间段"], ["all", "整个课程"]].map(([value, label]) => <button key={value} disabled={value === "this" ? !occurrenceKey : value === "slot" ? !slotId : false} onClick={() => setScope(value as Scope)} className={`rounded-xl border px-3 py-2 text-sm font-bold disabled:opacity-35 ${scope === value ? "border-orange-500 bg-orange-500 text-stone-950" : "border-app"}`}>{label}</button>)}</div></div>}
    {error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/50 dark:text-red-200">{error}</p>}
    </div><div className="safe-bottom mt-5 flex gap-2"><button disabled={busy} onClick={() => void save()} className="min-h-11 flex-1 rounded-xl bg-orange-500 px-5 py-3 font-bold text-stone-950 disabled:opacity-50">{busy ? "保存中..." : "保存"}</button>{item && <button disabled={busy} onClick={() => void remove()} className="min-h-11 rounded-xl border border-red-300 px-4 font-bold text-danger dark:border-red-900">删除</button>}</div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}