import { useMemo, useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ChevronDown, ChevronUp, Pencil, Plus, Trash2, X } from "lucide-react";
import { expandItems, isCalendarKind, type ExpandedItem, type SchedulePeriod, type SchedulePeriodInput, type Tag } from "@calendar/domain";
import { api, apiJson } from "../lib/api";
import { cacheSchedulePeriods, getCachedSchedulePeriods } from "../lib/offline";
import { CourseEditor } from "./CourseEditor";
import { readableTextColor } from "../lib/colors";
import { PRIORITY_META } from "../lib/priority";

interface CourseTimetableProps {
  items: ExpandedItem[];
  tags: Tag[];
  anchor: Date;
  semesterStartDate: string | null;
  onChanged: () => void;
}

function mondayOf(date: Date): Date { const value = new Date(date); const day = value.getDay(); value.setHours(0, 0, 0, 0); value.setDate(value.getDate() - (day === 0 ? 6 : day - 1)); return value; }
function localDate(value: Date): string { return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, "0")}-${String(value.getDate()).padStart(2, "0")}`; }
function minutes(value: string): number { const [hour, minute] = value.split(":").map(Number); return (hour ?? 0) * 60 + (minute ?? 0); }
function toDateAt(day: Date, time: string): Date { const date = new Date(day); const [hour, minute] = time.split(":").map(Number); date.setHours(hour ?? 0, minute ?? 0, 0, 0); return date; }
function occurrenceForDay(occurrence: { start: Date; end: Date }, day: Date): { start: Date; end: Date } | null {
  const dayStart = new Date(day); dayStart.setHours(0, 0, 0, 0);
  const dayEnd = new Date(dayStart); dayEnd.setDate(dayEnd.getDate() + 1);
  if (occurrence.end <= dayStart || occurrence.start >= dayEnd) return null;
  return { start: new Date(Math.max(occurrence.start.getTime(), dayStart.getTime())), end: new Date(Math.min(occurrence.end.getTime(), dayEnd.getTime())) };
}
function periodSpan(day: Date, occurrence: { start: Date; end: Date }, periods: SchedulePeriod[]) {
  const windowStart = occurrence.start.getDate() === day.getDate() && occurrence.start.getMonth() === day.getMonth() ? occurrence.start : toDateAt(day, "00:00");
  const windowEnd = occurrence.end.getTime() > windowStart.getTime() ? occurrence.end : new Date(windowStart.getTime() + 60 * 60_000);
  const startIndex = periods.findIndex((period) => minutes(period.endTime) > windowStart.getHours() * 60 + windowStart.getMinutes());
  let endIndex = periods.findIndex((period) => minutes(period.startTime) >= windowEnd.getHours() * 60 + windowEnd.getMinutes());
  if (endIndex < 0) endIndex = periods.length;
  if (startIndex < 0) return null;
  return { startIndex, endIndex: Math.max(startIndex + 1, endIndex) };
}

export function CourseTimetable({ items, tags, anchor, semesterStartDate, onChanged }: CourseTimetableProps) {
  const queryClient = useQueryClient(); const [editing, setEditing] = useState(false); const [draftPeriods, setDraftPeriods] = useState<SchedulePeriodInput[]>([]); const [message, setMessage] = useState(""); const [courseEditorOpen, setCourseEditorOpen] = useState(false); const [editingCourse, setEditingCourse] = useState<ExpandedItem | null>(null); const [editingOccurrence, setEditingOccurrence] = useState<string | null>(null); const [editingSlot, setEditingSlot] = useState<string | null>(null); const [courseDefaults, setCourseDefaults] = useState<{ startAt: string; endAt: string } | null>(null);
  const periodsQuery = useQuery({ queryKey: ["schedule-periods"], queryFn: async () => { try { const remote = await api<{ periods: SchedulePeriod[] }>("/api/v1/schedule-periods"); await cacheSchedulePeriods(remote.periods); return remote; } catch { return { periods: await getCachedSchedulePeriods() }; } } });
  const periods = periodsQuery.data?.periods ?? [];
  const weekStart = mondayOf(anchor); const weekEnd = new Date(weekStart); weekEnd.setDate(weekEnd.getDate() + 7); weekEnd.setMilliseconds(-1); const days = Array.from({ length: 7 }, (_, index) => { const day = new Date(weekStart); day.setDate(day.getDate() + index); return day; });
  const occurrences = useMemo(() => expandItems(items, weekStart, weekEnd, semesterStartDate ? new Date(`${semesterStartDate}T12:00:00`) : null).filter((occurrence) => occurrence.item.showInTimetable && isCalendarKind(occurrence.item.kind)), [items, semesterStartDate, weekStart.getTime(), weekEnd.getTime()]);
  const allDay = occurrences.filter((occurrence) => occurrence.allDay);
  async function savePeriods() { try { const response = await apiJson<{ periods: SchedulePeriod[] }>("/api/v1/schedule-periods", "PUT", { periods: draftPeriods.map((period, index) => ({ ...period, sortOrder: index })) }); queryClient.setQueryData(["schedule-periods"], response); setEditing(false); setMessage("节次已保存"); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  function startEditing() { setDraftPeriods(periods.map((period) => ({ name: period.name, startTime: period.startTime, endTime: period.endTime, sortOrder: period.sortOrder }))); setEditing(true); }
  function updatePeriod(index: number, patch: Partial<SchedulePeriodInput>) { setDraftPeriods((current) => current.map((period, position) => position === index ? { ...period, ...patch } : period)); }
  const [selection, setSelection] = useState<{ startDay: number; startPeriod: number; endDay: number; endPeriod: number } | null>(null); const selectionRef = useRef<typeof selection>(null); const draggingRef = useRef(false);
  function updateSelection(next: { startDay: number; startPeriod: number; endDay: number; endPeriod: number } | null) { selectionRef.current = next; setSelection(next); }
  function selectionTarget(event: PointerEvent | ReactPointerEvent) { const element = document.elementFromPoint(event.clientX, event.clientY)?.closest<HTMLElement>("[data-course-cell]"); if (!element) return null; return { day: Number(element.dataset.courseDay), period: Number(element.dataset.coursePeriod) }; }
  function beginSelection(event: ReactPointerEvent<HTMLButtonElement>, day: number, period: number) { if (event.button !== 0) return; event.preventDefault(); draggingRef.current = true; (event.currentTarget.closest(".course-grid") as HTMLElement | null)?.setPointerCapture(event.pointerId); updateSelection({ startDay: day, startPeriod: period, endDay: day, endPeriod: period }); }
  function moveSelection(event: ReactPointerEvent<HTMLDivElement>) { if (!draggingRef.current || !selectionRef.current) return; const target = selectionTarget(event); if (!target) return; const start = selectionRef.current; updateSelection({ startDay: Math.min(start.startDay, target.day), endDay: Math.max(start.startDay, target.day), startPeriod: Math.min(start.startPeriod, target.period), endPeriod: Math.max(start.startPeriod, target.period) }); }
  function finishSelection() { const value = selectionRef.current; draggingRef.current = false; updateSelection(null); if (!value) return; const firstDay = days[value.startDay]; const lastDay = days[value.endDay]; const firstPeriod = periods[value.startPeriod]; const lastPeriod = periods[value.endPeriod]; if (firstDay && lastDay && firstPeriod && lastPeriod) { setEditingCourse(null); setEditingOccurrence(null); setEditingSlot(null); setCourseDefaults({ startAt: toDateAt(firstDay, firstPeriod.startTime).toISOString(), endAt: toDateAt(lastDay, lastPeriod.endTime).toISOString() }); setCourseEditorOpen(true); } }
  function openCourse(item: ExpandedItem, occurrenceKey: string) { const parts = occurrenceKey.split(":"); const slotId = item.courseSlots.find((slot) => parts.includes(slot.id ?? ""))?.id ?? null; setEditingCourse(item); setEditingOccurrence(occurrenceKey); setEditingSlot(slotId); setCourseDefaults(null); setCourseEditorOpen(true); }
  function selected(day: number, period: number) { return Boolean(selection && day >= selection.startDay && day <= selection.endDay && period >= selection.startPeriod && period <= selection.endPeriod); }
  function movePeriod(index: number, direction: number) { const target = index + direction; if (target < 0 || target >= draftPeriods.length) return; setDraftPeriods((current) => { const next = [...current]; const [value] = next.splice(index, 1); next.splice(target, 0, value!); return next; }); }  return <section className="course-timetable">
    <div className="mb-3 flex flex-wrap items-center gap-2"><div><h2 className="text-lg font-black">课程表</h2><p className="muted text-xs">只显示编辑器里勾选“显示在课程表”的日程</p></div><button onClick={startEditing} className="ml-auto flex items-center gap-2 rounded-xl border border-app px-3 py-2 text-sm font-bold"><Pencil size={15}/>编辑节次</button></div>
    {allDay.length > 0 && <div className="mb-3 rounded-2xl border border-app p-3"><p className="mb-2 text-xs font-bold muted">全天安排</p><div className="flex flex-wrap gap-2">{allDay.map((occurrence) => <button key={occurrence.occurrenceKey} onClick={() => openCourse(occurrence.item, occurrence.occurrenceKey)} className="rounded-xl px-3 py-2 text-sm font-bold" style={{ backgroundColor: tags.find((tag) => occurrence.item.tagIds.includes(tag.id))?.color ?? PRIORITY_META[occurrence.item.priority].eventColor, color: readableTextColor(tags.find((tag) => occurrence.item.tagIds.includes(tag.id))?.color ?? PRIORITY_META[occurrence.item.priority].eventColor) }}>{occurrence.item.title}</button>)}</div></div>}
    {periods.length === 0 ? <div className="rounded-2xl border border-dashed border-app p-8 text-center muted">正在加载节次…</div> : <div className="course-scroll"><div className="course-grid" onPointerMove={moveSelection} onPointerUp={finishSelection} onPointerCancel={finishSelection} style={{ gridTemplateColumns: `72px repeat(7, minmax(108px, 1fr))`, gridTemplateRows: `52px repeat(${periods.length}, 88px)` }}>
      <div className="course-corner">节次</div>{days.map((day) => <div key={day.toISOString()} className="course-day-head"><strong>{["周一","周二","周三","周四","周五","周六","周日"][days.indexOf(day)]}</strong><span>{new Intl.DateTimeFormat("zh-CN", { month: "2-digit", day: "2-digit" }).format(day)}</span></div>)}
      {periods.flatMap((period, periodIndex) => [<div key={`label-${period.id}`} className="course-period-label" style={{ gridColumn: 1, gridRow: periodIndex + 2 }}><strong>{period.name}</strong><span>{period.startTime}</span><span>{period.endTime}</span></div>, ...days.map((day, dayIndex) => <button key={`${period.id}-${dayIndex}`} data-course-cell data-course-day={dayIndex} data-course-period={periodIndex} onPointerDown={(event) => beginSelection(event, dayIndex, periodIndex)} className={`course-empty ${selected(dayIndex, periodIndex) ? "course-cell-selected" : ""}`} style={{ gridColumn: dayIndex + 2, gridRow: periodIndex + 2 }} aria-label={`拖选或新建${period.name}课程`}/>)] )}
      {occurrences.filter((occurrence) => !occurrence.allDay).flatMap((occurrence) => days.map((day, dayIndex) => { const onDay = occurrenceForDay(occurrence, day); if (!onDay) return null; const span = periodSpan(day, onDay, periods); if (!span) return null; const tag = tags.find((value) => occurrence.item.tagIds.includes(value.id)); const color = occurrence.item.timetableColor ?? tag?.color ?? PRIORITY_META[occurrence.item.priority].eventColor; const conflict = occurrences.some((other) => other.occurrenceKey !== occurrence.occurrenceKey && !other.allDay && days.some((otherDay) => otherDay.toDateString() === day.toDateString() && occurrenceForDay(other, otherDay) && periodSpan(day, occurrenceForDay(other, otherDay)!, periods) && periodSpan(day, occurrenceForDay(other, otherDay)!, periods)!.startIndex < span.endIndex && periodSpan(day, occurrenceForDay(other, otherDay)!, periods)!.endIndex > span.startIndex)); return <button key={`${occurrence.occurrenceKey}-${dayIndex}`} onClick={() => openCourse(occurrence.item, occurrence.occurrenceKey)} className="course-event" style={{ gridColumn: dayIndex + 2, gridRow: `${span.startIndex + 2} / ${span.endIndex + 2}`, "--course-color": color } as CSSProperties}><span className="course-event-title">{occurrence.item.title}</span>{occurrence.item.location && <span className="course-event-location">@{occurrence.item.location}</span>}{conflict && <span className="course-conflict">冲突</span>}</button>; }))}
    </div></div>}
    {editing && <div className="fixed inset-0 z-[70] grid place-items-center bg-stone-950/45 p-4" onClick={() => setEditing(false)}><div className="max-h-[88vh] w-full max-w-2xl overflow-y-auto rounded-3xl border border-app bg-[var(--surface)] p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><h3 className="text-lg font-black">编辑节次</h3><button onClick={() => setEditing(false)} className="rounded-full p-2 hover-surface"><X size={17}/></button></div><p className="muted mt-1 text-sm">修改会作用于整个工作区的课表。</p><div className="mt-4 space-y-2">{draftPeriods.map((period, index) => <div key={index} className="grid gap-2 rounded-2xl border border-app p-3 sm:grid-cols-[80px_1fr_1fr_auto]"><input value={period.name} onChange={(event) => updatePeriod(index, { name: event.target.value })} className="rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2 font-bold" placeholder="名称"/><input type="time" value={period.startTime} onChange={(event) => updatePeriod(index, { startTime: event.target.value })} className="rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2"/><input type="time" value={period.endTime} onChange={(event) => updatePeriod(index, { endTime: event.target.value })} className="rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2"/><div className="flex gap-1"><button onClick={() => movePeriod(index, -1)} className="rounded-lg border border-app p-2" title="上移"><ChevronUp size={15}/></button><button onClick={() => movePeriod(index, 1)} className="rounded-lg border border-app p-2" title="下移"><ChevronDown size={15}/></button><button onClick={() => setDraftPeriods((current) => current.filter((_, position) => position !== index))} className="rounded-lg border border-red-300 p-2 text-danger dark:border-red-900" title="删除"><Trash2 size={15}/></button></div></div>)}</div><button onClick={() => setDraftPeriods((current) => [...current, { name: String(current.length + 1), startTime: "08:00", endTime: "08:45", sortOrder: current.length }])} className="mt-3 flex items-center gap-2 rounded-xl border border-dashed border-app px-3 py-2 text-sm font-bold"><Plus size={15}/>添加节次</button><div className="mt-5 flex gap-2"><button disabled={draftPeriods.length === 0} onClick={() => void savePeriods()} className="flex-1 rounded-xl bg-orange-500 px-4 py-3 font-bold text-stone-950 disabled:opacity-50">保存节次</button><button onClick={() => setEditing(false)} className="rounded-xl border border-app px-4 py-3 font-bold">取消</button></div>{message && <p className="mt-3 text-sm text-orange-700 dark:text-orange-200">{message}</p>}</div></div>}
    <CourseEditor open={courseEditorOpen} item={editingCourse} occurrenceKey={editingOccurrence} slotId={editingSlot} defaults={courseDefaults} tags={tags} onClose={() => setCourseEditorOpen(false)} onSaved={() => { onChanged(); }} />
  </section>;
}
