import { useEffect, useMemo, useRef, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { CalendarDays, Check, Copy, Image as ImageIcon, Layers3, ListTodo, Paperclip, Trash2, X } from "lucide-react";
import { isTaskKind, type ExpandedItem, type Item, type ItemKind, type Recurrence, type Tag } from "@calendar/domain";
import { ApiError, api, apiJson } from "../lib/api";
import { queueMutation, upsertCachedItem, removeCachedItem } from "../lib/offline";
import { readableTextColor } from "../lib/colors";
import { getAttachmentPreviewUrl, openAttachment, uploadAttachment } from "../lib/attachments";

interface ItemEditorProps { open: boolean; item?: (ExpandedItem | Item) | null; occurrenceKey?: string | null; defaultStartAt?: string | null; defaultEndAt?: string | null; defaultIsAllDay?: boolean; defaultKind?: ItemKind; defaultShowInTimetable?: boolean; defaultRecurrenceFrequency?: "" | Recurrence["frequency"]; semesterStartDate?: string | null; demoMode?: boolean; tags: Tag[]; items: ExpandedItem[]; onClose: () => void; onSaved: (item: Item) => void; onDeleted: (id: string) => void; }
interface FormState { kind: ItemKind; title: string; description: string; location: string; startAt: string; endAt: string; dueAt: string; isAllDay: boolean; timezone: string; priority: "none" | "low" | "medium" | "high" | "urgent"; status: "active" | "partial" | "completed" | "cancelled"; autoRollover: boolean; showInTimetable: boolean; endConfirmation: boolean; recurrenceFrequency: "" | Recurrence["frequency"]; recurrenceInterval: number; recurrenceWeekParity: "all" | "odd" | "even"; reminderTrigger: "before_start" | "at_start" | "at_end"; reminderOffsets: number[]; tagIds: string[]; parentId: string | null; }
const KIND_OPTIONS = [["event", "日程", "仅日历", CalendarDays], ["task", "任务", "仅待办池", ListTodo], ["both", "日程+任务", "两处显示", Layers3]] as const;

function localInput(value?: string | null): string { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
function toIso(value: string): string | null { return value ? new Date(value).toISOString() : null; }
function defaultStart(date?: Date | null) { const value = date ? new Date(date) : new Date(); value.setMinutes(Math.ceil(value.getMinutes() / 15) * 15, 0, 0); return value; }
function initialState(item?: (ExpandedItem | Item) | null, defaults?: { startAt?: string | null; endAt?: string | null; isAllDay?: boolean; showInTimetable?: boolean } | null, defaultKind: ItemKind = "event", defaultRecurrenceFrequency: "" | Recurrence["frequency"] = ""): FormState {
  const suggestedStart = defaultStart(defaults?.startAt ? new Date(defaults.startAt) : null);
  const start = item?.startAt ?? (defaultKind === "task" ? null : defaults?.startAt ?? suggestedStart.toISOString());
  const end = item?.endAt ?? (defaultKind === "task" ? null : defaults?.endAt ?? new Date(suggestedStart.getTime() + 3600000).toISOString());
  return { kind: item?.kind ?? defaultKind, title: item?.title ?? "", description: item?.description ?? "", location: item?.location ?? "", startAt: localInput(start), endAt: localInput(end), dueAt: localInput(item?.dueAt), isAllDay: item?.isAllDay ?? defaults?.isAllDay ?? false, timezone: item?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone, priority: item?.priority ?? "none", status: item?.status === "completed" ? "completed" : item?.status === "partial" ? "partial" : "active", autoRollover: item?.autoRollover ?? false, showInTimetable: item?.showInTimetable ?? defaults?.showInTimetable ?? false, endConfirmation: item ? item.reminders?.some((rule) => rule.trigger === "at_end") ?? false : defaultKind === "task" || defaultKind === "both", recurrenceFrequency: item?.recurrence?.frequency ?? defaultRecurrenceFrequency, recurrenceInterval: item?.recurrence?.interval ?? 1, recurrenceWeekParity: item?.recurrence?.weekParity ?? "all", reminderTrigger: item?.reminders?.[0]?.trigger ?? "before_start", reminderOffsets: item?.reminders?.map((rule) => rule.offsetMinutes) ?? [15], tagIds: item?.tagIds ?? [], parentId: item?.parentId ?? null };
}

export function ItemEditor({ open, item, occurrenceKey, defaultStartAt, defaultEndAt, defaultIsAllDay = false, defaultKind = "event", defaultShowInTimetable = false, defaultRecurrenceFrequency = "", semesterStartDate = null, demoMode = false, tags, items, onClose, onSaved, onDeleted }: ItemEditorProps) {
  const [form, setForm] = useState<FormState>(() => initialState(item, { startAt: defaultStartAt, endAt: defaultEndAt, isAllDay: defaultIsAllDay, showInTimetable: defaultShowInTimetable }, defaultKind, defaultRecurrenceFrequency)); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [conflicts, setConflicts] = useState<Array<{ title: string; startAt: string; endAt: string }>>([]);
  const [applyScope, setApplyScope] = useState<"this" | "all">("all"); const [attachments, setAttachments] = useState<Array<{ id: string; fileName: string; mimeType: string; size: number }>>([]); const [previewUrls, setPreviewUrls] = useState<Record<string, string>>({}); const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { if (open) { setForm(initialState(item, { startAt: defaultStartAt, endAt: defaultEndAt, isAllDay: defaultIsAllDay, showInTimetable: defaultShowInTimetable }, defaultKind, defaultRecurrenceFrequency)); setError(""); setConflicts([]); setAttachments([]); if (item?.id && !demoMode) void api<{ attachments: typeof attachments }>(`/api/v1/items/${item.id}/attachments`).then((value) => setAttachments(value.attachments)).catch(() => undefined); } }, [open, item, defaultStartAt, defaultEndAt, defaultIsAllDay, defaultKind]);
  useEffect(() => { if (!item?.id || demoMode) return; let cancelled = false; const images = attachments.filter((attachment) => attachment.mimeType.startsWith("image/")); void Promise.all(images.map(async (attachment) => { const url = await getAttachmentPreviewUrl(attachment.id).catch(() => null); if (url && !cancelled) setPreviewUrls((current) => ({ ...current, [attachment.id]: url })); return url; })).then((urls) => { if (cancelled) urls.filter(Boolean).forEach((url) => URL.revokeObjectURL(url!)); }); return () => { cancelled = true; }; }, [item?.id, attachments, demoMode]);
  function adjustTime(field: "startAt" | "endAt", minutes: number) { setForm((current) => { if (!current[field]) { if (field === "endAt" && !current.startAt) { setError("请先设置开始时间"); return current; } } const base = current[field] ? new Date(current[field]) : defaultStart(null); const next = new Date(base.getTime() + minutes * 60000); if (field === "startAt" && current.endAt && next >= new Date(current.endAt)) { setError("开始时间必须早于结束时间"); return current; } if (field === "endAt" && current.startAt && next <= new Date(current.startAt)) { setError("结束时间必须晚于开始时间"); return current; } setError(""); return { ...current, [field]: localInput(next.toISOString()) }; }); }
  function setDuration(minutes: number) { setForm((current) => { if (!current.startAt) { setError("请先设置开始时间"); return current; } setError(""); return { ...current, endAt: localInput(new Date(new Date(current.startAt).getTime() + minutes * 60000).toISOString()) }; }); }
  function changeKind(kind: ItemKind) { setForm((current) => { if (kind === "event" && !current.startAt) { const start = defaultStartAt ? new Date(defaultStartAt) : defaultStart(null); const end = defaultEndAt ? new Date(defaultEndAt) : new Date(start.getTime() + 3600000); return { ...current, kind, startAt: localInput(start.toISOString()), endAt: localInput(end.toISOString()), isAllDay: defaultIsAllDay }; } return { ...current, kind }; }); }
    const patch = useMemo(() => ({ kind: form.kind, title: form.title.trim(), description: form.description, location: form.location, startAt: toIso(form.startAt), endAt: toIso(form.endAt), dueAt: toIso(form.dueAt), isAllDay: form.isAllDay, timezone: form.timezone, priority: form.priority, status: form.status, completedAt: form.status === "completed" ? new Date().toISOString() : null, autoRollover: form.autoRollover, showInTimetable: form.showInTimetable, parentId: form.parentId, recurrence: form.recurrenceFrequency ? { frequency: form.recurrenceFrequency, interval: form.recurrenceInterval, byWeekday: [], byMonthDay: [], weekParity: form.recurrenceWeekParity, count: null, until: null } : null, reminders: [...form.reminderOffsets.map((offsetMinutes) => ({ trigger: form.reminderTrigger, offsetMinutes, channels: ["in_app", "browser_push"] as string[], repeatEveryMinutes: form.reminderTrigger === "at_end" ? 0 : 5, enabled: true })), ...(form.endConfirmation && form.reminderTrigger !== "at_end" ? [{ trigger: "at_end" as const, offsetMinutes: 0 as const, channels: ["in_app", "browser_push"] as string[], repeatEveryMinutes: 0, enabled: true }] : [])], tagIds: form.tagIds }), [form]);
  async function save(force = false) {
    if (!patch.title) { setError("请输入标题"); return; } setBusy(true); setError("");
    try {
      if (occurrenceKey && applyScope === "this") { await apiJson(`/api/v1/items/${item?.id}/exceptions/${encodeURIComponent(occurrenceKey)}`, "PUT", { action: "override", override: patch }); onSaved({ ...(item as Item), ...patch, id: item!.id } as Item); onClose(); return; }
      const suffix = force ? "?force=true" : ""; const response = item?.id ? await apiJson<{ item: Item }>(`/api/v1/items/${item.id}${suffix}`, "PATCH", { ...patch, baseVersion: item.version }) : await apiJson<{ item: Item }>(`/api/v1/items${suffix}`, "POST", patch);
      void upsertCachedItem(response.item).catch(() => undefined); onSaved(response.item); onClose();
    } catch (cause) {
      if (cause instanceof ApiError && cause.status === 409 && cause.code === "CONFLICT") { setConflicts((cause.payload as { conflicts: typeof conflicts }).conflicts); setBusy(false); return; }
      if (cause instanceof TypeError) { const id = item?.id ?? crypto.randomUUID(); const now = new Date().toISOString(); const local = { ...patch, id, workspaceId: item?.workspaceId ?? "offline", calendarId: item?.calendarId ?? null, version: item?.version ?? 0, createdAt: item?.createdAt ?? now, updatedAt: now, deletedAt: null, timetableColor: item?.timetableColor ?? null, courseSlots: item?.courseSlots ?? [], recurrenceExceptions: [] } as Item; void upsertCachedItem(local).catch(() => undefined); void queueMutation({ entity: "item", action: item ? "update" : "create", entityId: id, baseVersion: item?.version, fields: patch as unknown as Record<string, unknown> }).catch(() => undefined); onSaved(local); onClose(); return; }
      setError(cause instanceof Error ? cause.message : "保存失败");
    } finally { setBusy(false); }
  }
  async function upload(file: File) { if (!item?.id) return; try { const attachment = await uploadAttachment(item.id, file); setAttachments((value) => [...value, attachment]); } catch (cause) { setError(cause instanceof Error ? cause.message : "上传失败"); } }
  async function remove() { if (!item?.id || !window.confirm("删除此日程？回收站保留 30 天。")) return; setBusy(true); setError(""); try { await apiJson(`/api/v1/items/${item.id}`, "DELETE"); onDeleted(item.id); void removeCachedItem(item.id).catch(() => undefined); onClose(); } catch (cause) { if (cause instanceof TypeError) { onDeleted(item.id); void removeCachedItem(item.id).catch(() => undefined); void queueMutation({ entity: "item", action: "delete", entityId: item.id, fields: {} }).catch(() => undefined); onClose(); } else { setError(cause instanceof Error ? cause.message : "删除失败"); } } finally { setBusy(false); } }
  async function copy() { if (!item?.id) return; setBusy(true); try { const value = await apiJson<{ item: Item }>(`/api/v1/items/${item.id}/copy`, "POST", {}); void upsertCachedItem(value.item).catch(() => undefined); onSaved(value.item); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "复制失败"); } finally { setBusy(false); } }  const field = "w-full rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5";
  const label = "text-xs font-bold text-secondary";
  return <Dialog.Root open={open} onOpenChange={(next) => !next && onClose()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-stone-950/40 backdrop-blur-sm"/><Dialog.Content className="fixed inset-x-0 bottom-0 z-50 max-h-[94vh] overflow-y-auto rounded-t-[2rem] border border-app bg-[var(--surface)] p-5 shadow-2xl md:left-1/2 md:top-1/2 md:bottom-auto md:w-[min(720px,92vw)] md:-translate-x-1/2 md:-translate-y-1/2 md:rounded-[2rem]">
    <div className="mx-auto mb-4 h-1.5 w-12 rounded-full bg-stone-300 md:hidden"/><div className="mb-5 flex items-center justify-between"><div><Dialog.Title className="text-xl font-black">{item ? "编辑" : "新建"}{form.kind === "both" ? "日程+任务" : form.kind === "task" ? "任务" : "日程"}</Dialog.Title><Dialog.Description className="muted text-sm">设置时间、任务属性与提醒</Dialog.Description></div><Dialog.Close className="grid size-10 place-items-center rounded-full hover-surface"><X size={20}/></Dialog.Close></div>
    {occurrenceKey && <div className="mb-4 grid grid-cols-2 gap-2 rounded-2xl bg-orange-50 p-2 dark:bg-orange-950/40"><button onClick={() => setApplyScope("this")} className={`rounded-xl px-3 py-2 text-sm font-bold ${applyScope === "this" ? "bg-orange-500 text-stone-950" : ""}`}>仅修改本次</button><button onClick={() => setApplyScope("all")} className={`rounded-xl px-3 py-2 text-sm font-bold ${applyScope === "all" ? "bg-orange-500 text-stone-950" : ""}`}>修改全部</button></div>}
    <div className="space-y-4">
      <div className="rounded-2xl border border-app p-2"><div className="grid grid-cols-3 gap-2">{KIND_OPTIONS.map(([value, label, hint, Icon]) => { const active = form.kind === value; return <button key={String(value)} type="button" aria-pressed={active} onClick={() => changeKind(value as ItemKind)} className={`relative flex min-h-20 flex-col items-center justify-center gap-1 rounded-xl border-2 px-2 py-3 transition ${active ? "border-orange-500 bg-orange-50 text-orange-800 dark:bg-orange-950/50 dark:text-orange-100" : "border-transparent surface-muted hover-surface text-secondary"}`}><Icon size={20}/><span className="text-xs font-bold">{String(label)}</span><span className="text-[10px] leading-tight opacity-80">{String(hint)}</span>{active && <span className="absolute right-1 top-1 grid size-5 place-items-center rounded-full bg-orange-500 text-stone-950"><Check size={12} strokeWidth={3}/></span>}</button>; })}</div><p className="muted mt-2 text-xs">{form.kind === "event" ? "只显示在日历，必须设置开始时间。" : form.kind === "task" ? "只显示在待办池，可以暂时不设置时间。" : "始终显示在待办池；设置开始时间后也会显示在日历。"}</p></div>
      <label><span className={label}>标题 *</span><input autoFocus className={`${field} mt-1 text-lg font-bold`} value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="要做什么？" /></label>
      <div className="grid gap-4 sm:grid-cols-2"><label><span className={label}>开始</span><input type="datetime-local" className={`${field} mt-1`} value={form.startAt} onChange={(event) => setForm({ ...form, startAt: event.target.value })} /></label><label><span className={label}>结束</span><input type="datetime-local" className={`${field} mt-1`} value={form.endAt} onChange={(event) => setForm({ ...form, endAt: event.target.value })} /></label></div><div className="mt-2 rounded-xl surface-muted p-2 text-xs"><div className="flex flex-wrap items-center gap-1.5"><span className="mr-1 font-bold">开始</span><button type="button" aria-label="开始时间减15分钟" onClick={() => adjustTime("startAt", -15)} className="rounded-lg border border-app px-2 py-1">-15 分</button><button type="button" aria-label="开始时间加15分钟" onClick={() => adjustTime("startAt", 15)} className="rounded-lg border border-app px-2 py-1">+15 分</button><span className="ml-2 mr-1 font-bold">结束</span><button type="button" aria-label="结束时间减15分钟" onClick={() => adjustTime("endAt", -15)} className="rounded-lg border border-app px-2 py-1">-15 分</button><button type="button" aria-label="结束时间加15分钟" onClick={() => adjustTime("endAt", 15)} className="rounded-lg border border-app px-2 py-1">+15 分</button><span className="ml-2 mr-1 font-bold">时长</span>{[[15, "15 分"], [30, "30 分"], [60, "1 小时"], [120, "2 小时"]].map(([minutes, text]) => <button key={String(minutes)} type="button" aria-label={`设置时长为${String(text)}`} onClick={() => setDuration(Number(minutes))} className="rounded-lg border border-app px-2 py-1">{String(text)}</button>)}</div></div>
      <div className="flex flex-wrap items-center gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={form.isAllDay} onChange={(event) => setForm({ ...form, isAllDay: event.target.checked })}/>全天</label><label className="flex items-center gap-2">优先级<select className={field} value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value as FormState["priority"] })}><option value="none">无</option><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option></select></label><label className="flex items-center gap-2">状态<select className={field} value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as FormState["status"] })}><option value="active">未完成</option><option value="partial">部分完成</option><option value="completed">已完成</option><option value="cancelled">已取消</option></select></label></div>{(form.kind === "task" || form.kind === "both") && <div className="grid gap-2 sm:grid-cols-2"><label className="flex items-start gap-2 rounded-xl border border-app p-3 text-sm"><input type="checkbox" checked={form.autoRollover} onChange={(event) => setForm({ ...form, autoRollover: event.target.checked })}/><span><strong className="block">未完成时提供顺延建议</strong><span className="muted text-xs">仅提示，确认后才会修改时间</span></span></label><label className="flex items-start gap-2 rounded-xl border border-app p-3 text-sm"><input type="checkbox" checked={form.endConfirmation} onChange={(event) => setForm({ ...form, endConfirmation: event.target.checked })}/><span><strong className="block">结束时确认结果</strong><span className="muted text-xs">完成、部分完成、未完成或取消</span></span></label></div>}{(form.kind === "event" || form.kind === "both") && <label className="mt-2 flex items-start gap-2 rounded-xl border border-app p-3 text-sm"><input type="checkbox" checked={form.showInTimetable} onChange={(event) => setForm({ ...form, showInTimetable: event.target.checked })}/><span><strong className="block">显示在课程表</strong><span className="muted text-xs">开启后会同时出现在日历和课表</span></span></label>}
      <div className="grid gap-4 sm:grid-cols-2"><label><span className={label}>地点</span><input className={`${field} mt-1`} value={form.location} onChange={(event) => setForm({ ...form, location: event.target.value })} /></label><label><span className={label}>截止时间</span><input type="datetime-local" className={`${field} mt-1`} value={form.dueAt} onChange={(event) => setForm({ ...form, dueAt: event.target.value })} /></label></div>
      <label><span className={label}>备注</span><textarea rows={3} className={`${field} mt-1`} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label>
      <div><p className={label}>标签</p><div className="mt-2 flex flex-wrap gap-2">{tags.length === 0 ? <span className="muted text-sm">暂无标签，可在设置页创建。</span> : tags.map((tag) => <button key={tag.id} onClick={() => setForm({ ...form, tagIds: form.tagIds.includes(tag.id) ? form.tagIds.filter((id) => id !== tag.id) : [...form.tagIds, tag.id] })} className={`rounded-full border px-3 py-1.5 text-xs font-bold `} style={{ backgroundColor: form.tagIds.includes(tag.id) ? tag.color : undefined, color: form.tagIds.includes(tag.id) ? readableTextColor(tag.color) : undefined, borderColor: tag.color }}>{tag.name}</button>)}</div></div>
      {form.kind === "task" && !item?.parentId && <label><span className={label}>父任务</span><select className={`${field} mt-1`} value={form.parentId ?? ""} onChange={(event) => setForm({ ...form, parentId: event.target.value || null })}><option value="">无</option>{items.filter((value) => isTaskKind(value.kind) && value.id !== item?.id && !value.parentId).map((value) => <option key={value.id} value={value.id}>{value.title}</option>)}</select></label>}<div className="grid gap-4 sm:grid-cols-2"><label><span className={label}>重复</span><select className={`${field} mt-1`} value={form.recurrenceFrequency} onChange={(event) => setForm({ ...form, recurrenceFrequency: event.target.value as FormState["recurrenceFrequency"] })}><option value="">不重复</option><option value="daily">每天</option><option value="weekly">每周</option><option value="monthly">每月</option><option value="yearly">每年</option></select></label>{form.recurrenceFrequency === "weekly" && <label><span className={label}>单双周</span><select className={`${field} mt-1`} disabled={!semesterStartDate} value={form.recurrenceWeekParity} onChange={(event) => setForm({ ...form, recurrenceWeekParity: event.target.value as FormState["recurrenceWeekParity"] })}><option value="all">每周</option><option value="odd">单周</option><option value="even">双周</option></select>{!semesterStartDate && <span className="mt-1 block text-xs text-danger">请先在设置中填写学期第 1 周周一</span>}</label>}{form.recurrenceFrequency && <label><span className={label}>每隔</span><input type="number" min={1} className={`${field} mt-1`} value={form.recurrenceInterval} onChange={(event) => setForm({ ...form, recurrenceInterval: Number(event.target.value) })} /></label>}</div>
      <div><p className={label}>提醒</p><label className="mt-2 block"><span className="muted mb-1 block text-xs">提醒时机</span><select className={field} value={form.reminderTrigger} onChange={(event) => setForm({ ...form, reminderTrigger: event.target.value as FormState["reminderTrigger"] })}><option value="before_start">开始前</option><option value="at_start">开始时</option><option value="at_end">结束时确认</option></select></label><div className="mt-2 flex flex-wrap gap-2">{[0, 5, 15, 30, 60, 1440].map((offset) => <button key={offset} onClick={() => setForm({ ...form, reminderOffsets: form.reminderOffsets.includes(offset) ? form.reminderOffsets.filter((value) => value !== offset) : [...form.reminderOffsets, offset] })} className={`rounded-full px-3 py-1.5 text-xs font-bold ${form.reminderOffsets.includes(offset) ? "bg-orange-500 text-stone-950" : "border border-app"}`}>{offset === 0 ? "准时" : offset === 1440 ? "提前 1 天" : `提前 ${offset} 分钟`}</button>)}</div></div>
      {!demoMode && (      <div className="rounded-2xl border border-app p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-sm font-bold"><Paperclip size={16}/>附件</div><button disabled={!item?.id} onClick={() => fileInput.current?.click()} className="rounded-lg border border-app px-3 py-1.5 text-xs font-bold disabled:opacity-40">上传</button><input ref={fileInput} className="hidden" type="file" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); }}/></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{attachments.map((attachment) => <button key={attachment.id} onClick={() => void openAttachment(attachment.id)} className="rounded-xl border border-app p-2 text-left text-xs"><div className="mb-2 grid h-20 place-items-center overflow-hidden rounded-lg surface-muted">{attachment.mimeType.startsWith("image/") ? <img className="h-full w-full object-cover" src={previewUrls[attachment.id] ?? ""} alt={attachment.fileName}/> : attachment.mimeType === "application/pdf" ? <Paperclip/> : <ImageIcon/>}</div><span className="line-clamp-2 font-semibold">{attachment.fileName}</span></button>)}</div></div>)}
      {conflicts.length > 0 && <div className="rounded-2xl bg-red-50 p-4 text-sm text-red-800 dark:bg-red-950/50 dark:text-red-100"><strong>时间冲突</strong><ul className="mt-2 space-y-1">{conflicts.map((conflict) => <li key={`${conflict.title}-${conflict.startAt}`}>与「{conflict.title}」重叠：{new Date(conflict.startAt).toLocaleString("zh-CN")}</li>)}</ul><div className="mt-3 flex gap-2"><button disabled={busy} onClick={() => void save(true)} className="rounded-lg bg-red-600 px-3 py-2 font-bold text-white disabled:opacity-50">仍然保存</button><button onClick={() => setConflicts([])} className="rounded-lg border border-red-300 px-3 py-2">返回修改</button></div></div>}
      {error && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/50 dark:text-red-200">{error}</p>}
    </div>
    <div className="safe-bottom mt-6 flex flex-wrap items-center gap-2"><button disabled={busy} onClick={() => void save()} className="min-h-11 flex-1 rounded-xl bg-orange-500 px-5 py-3 font-bold text-stone-950 disabled:opacity-50">{busy ? "保存中..." : "保存"}</button>{item?.id && <button disabled={busy} onClick={() => void copy()} className="grid min-h-11 place-items-center rounded-xl border border-app px-3" title="复制"><Copy size={18}/></button>}{item?.id && <button disabled={busy} onClick={() => void remove()} className="grid min-h-11 place-items-center rounded-xl border border-red-300 dark:border-red-900 px-3 text-danger" title="删除"><Trash2 size={18}/></button>}</div>
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
