import { useEffect, useRef, useState } from "react";
import { AlarmClock, BellRing, Clock3, X } from "lucide-react";
import { api, apiJson } from "../lib/api";
import { playReminderSound, unlockReminderSound } from "../lib/reminderSound";

interface Delivery { id: string; itemId: string; occurrenceKey: string; itemTitle: string; scheduledAt: string; status: string; channel: string; trigger?: "before_start" | "at_start" | "at_end"; acknowledgedAt: string | null; }
interface Suggestion { startAt: string | null; endAt: string | null; dueAt: string | null; label: string; }
interface Outcome { itemId: string; occurrenceKey: string | null; outcome: "completed" | "partial" | "postponed" | "cancelled"; startAt?: string | null; endAt?: string | null; dueAt?: string | null; }

export function ReminderCenter({ onResolved, soundEnabled = true }: { onResolved?: () => void; soundEnabled?: boolean }) {
  const [deliveries, setDeliveries] = useState<Delivery[]>([]); const [busy, setBusy] = useState(false); const [suggestions, setSuggestions] = useState<Suggestion[] | null>(null); const [message, setMessage] = useState(""); const playedDeliveryIds = useRef<Set<string>>(new Set());
  async function load() { try { const response = await api<{ deliveries: Delivery[] }>("/api/v1/reminders/deliveries"); setDeliveries(response.deliveries.filter((value) => !value.acknowledgedAt)); } catch { /* offline */ } }
  useEffect(() => { void load(); let timer = 0; const schedule = () => { window.clearInterval(timer); timer = window.setInterval(() => void load(), document.visibilityState === "visible" ? 15000 : 60000); }; const online = () => void load(); const visibility = () => { schedule(); void load(); }; schedule(); window.addEventListener("online", online); document.addEventListener("visibilitychange", visibility); return () => { window.clearInterval(timer); window.removeEventListener("online", online); document.removeEventListener("visibilitychange", visibility); }; }, []);
  useEffect(() => { const unlock = () => { void unlockReminderSound(); }; window.addEventListener("pointerdown", unlock, { once: true }); window.addEventListener("keydown", unlock, { once: true }); return () => { window.removeEventListener("pointerdown", unlock); window.removeEventListener("keydown", unlock); }; }, []);
  useEffect(() => { const handler = (event: MessageEvent<{ type?: string; deliveryId?: string }>) => { if (event.data?.type !== "reminder-push" || !soundEnabled) return; const id = event.data.deliveryId; if (id && playedDeliveryIds.current.has(id)) return; if (id) playedDeliveryIds.current.add(id); void playReminderSound(); }; navigator.serviceWorker?.addEventListener("message", handler); return () => navigator.serviceWorker?.removeEventListener("message", handler); }, [soundEnabled]);
  const current = deliveries[0];
  useEffect(() => { const delivery = deliveries[0]; if (!soundEnabled || !delivery || playedDeliveryIds.current.has(delivery.id) || document.visibilityState !== "visible") return; playedDeliveryIds.current.add(delivery.id); void playReminderSound(); }, [deliveries, soundEnabled]);
  if (!current) return null; const currentDelivery = current; const currentId = currentDelivery.id; const isEnd = currentDelivery.trigger === "at_end";
  async function acknowledge() { setBusy(true); try { await apiJson(`/api/v1/reminders/deliveries/${currentId}/ack`, "POST"); setDeliveries((value) => value.slice(1)); setSuggestions(null); } finally { setBusy(false); } }
  async function snooze(minutes: number) { setBusy(true); try { await apiJson(`/api/v1/reminders/deliveries/${currentId}/snooze`, "POST", { minutes }); setDeliveries((value) => value.slice(1)); } finally { setBusy(false); } }
  async function resolve(outcome: Outcome["outcome"], extra: Partial<Outcome> = {}) { setBusy(true); try { await apiJson(`/api/v1/items/${currentDelivery.itemId}/resolve`, "POST", { occurrenceKey: currentDelivery.occurrenceKey && currentDelivery.occurrenceKey !== currentDelivery.itemId ? currentDelivery.occurrenceKey : null, outcome, ...extra }); setDeliveries((value) => value.slice(1)); setSuggestions(null); onResolved?.(); setMessage(outcome === "partial" ? "已标记为部分完成" : outcome === "cancelled" ? "已取消本次" : outcome === "postponed" ? "已顺延" : "已完成"); } catch (error) { setMessage(error instanceof Error ? error.message : "提交失败"); } finally { setBusy(false); } }
  async function loadSuggestions() { setBusy(true); setMessage(""); try { const value = await api<{ suggestions: Suggestion[] }>(`/api/v1/items/${currentDelivery.itemId}/rollover-suggestions?occurrenceKey=${encodeURIComponent(currentDelivery.occurrenceKey)}`); setSuggestions(value.suggestions); if (value.suggestions.length === 0) setMessage("未来 7 天暂无可用的顺延时间"); } catch { setMessage("顺延建议加载失败"); } finally { setBusy(false); } }
  return <aside className="fixed inset-x-3 top-3 z-[60] mx-auto max-w-xl rounded-3xl border border-orange-200 bg-white p-4 shadow-2xl shadow-orange-950/20 dark:border-orange-900 dark:bg-stone-900 md:right-6 md:left-auto md:top-6">
    <div className="flex gap-3"><div className="grid size-11 shrink-0 place-items-center rounded-2xl bg-orange-100 text-orange-600 dark:text-orange-400 dark:bg-orange-950"><BellRing/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wider text-orange-600 dark:text-orange-400">{isEnd ? "结束确认" : currentDelivery.status === "missed" ? "错过提醒" : "日程提醒"}</p><h3 className="truncate text-lg font-black">{currentDelivery.itemTitle}</h3><p className="muted mt-1 flex items-center gap-1 text-sm"><Clock3 size={14}/>{new Date(currentDelivery.scheduledAt).toLocaleString("zh-CN")}</p></div><button onClick={() => void acknowledge()} className="grid size-8 place-items-center rounded-full hover-surface"><X size={16}/></button></div>
      {isEnd ? <div className="mt-3 space-y-2">{suggestions ? <div className="rounded-2xl border border-app p-3"><p className="mb-2 text-sm font-bold">选择顺延时间</p><div className="space-y-1">{suggestions.map((suggestion) => <button disabled={busy} key={`${suggestion.startAt}-${suggestion.dueAt}`} onClick={() => void resolve("postponed", suggestion)} className="w-full rounded-xl border border-app px-3 py-2 text-left text-sm"><span className="font-bold">{suggestion.label}</span><span className="muted ml-2">{new Date(suggestion.startAt ?? suggestion.dueAt ?? "").toLocaleString("zh-CN")}</span></button>)}<button disabled={busy} onClick={() => setSuggestions(null)} className="w-full rounded-xl px-3 py-2 text-sm muted">返回</button></div></div> : <div className="flex flex-wrap gap-2"><button disabled={busy} onClick={() => void resolve("completed")} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-bold text-white">已完成</button><button disabled={busy} onClick={() => void resolve("partial")} className="rounded-xl bg-amber-500 px-3 py-2 text-sm font-bold text-stone-950">部分完成</button><button disabled={busy} onClick={() => void loadSuggestions()} className="rounded-xl border border-orange-400 px-3 py-2 text-sm font-bold text-orange-700 dark:text-orange-200">未完成，顺延</button><button disabled={busy} onClick={() => void resolve("cancelled")} className="rounded-xl border border-red-300 px-3 py-2 text-sm font-bold text-danger dark:border-red-900">取消本次</button></div>}</div> : <div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} onClick={() => void acknowledge()} className="rounded-xl bg-orange-500 px-3 py-2 text-sm font-bold text-stone-950">知道了</button>{[5,10,15,30].map((minutes) => <button disabled={busy} key={minutes} onClick={() => void snooze(minutes)} className="rounded-xl border border-app px-3 py-2 text-sm">稍后 {minutes} 分钟</button>)}</div>}
      {message && <p className="mt-2 text-xs text-orange-700 dark:text-orange-200">{message}</p>}
    </div></div>
    {deliveries.length > 1 && <p className="muted mt-3 flex items-center gap-1 text-xs"><AlarmClock size={13}/>另有 {deliveries.length - 1} 条提醒等待处理</p>}
  </aside>;
}