import { useEffect, useRef, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Bell, CloudDownload, CloudUpload, Download, Fingerprint, HardDrive, Moon, Plus, Rss, Sun, Trash2, X } from "lucide-react";
import { authClient } from "../auth";
import { api, apiJson } from "../lib/api";
import { playReminderSound } from "../lib/reminderSound";
import { clearLastSession, clearOfflineData, requestPersistentStorage } from "../lib/offline";
import { useInstallPrompt } from "../hooks/useInstallPrompt";
interface SettingsPanelProps { open: boolean; dark: boolean; onDarkChange: (value: boolean) => void; onClose: () => void; onDataChanged: () => void; demoMode?: boolean; demoExpiresAt?: string | null; onDemoReset?: () => void; onDemoLeave?: () => void; }

interface Subscription { id: string; name: string; url: string; lastFetchedAt: string | null; lastError: string | null; }
function normalizeSemesterDate(value: string | null | undefined): string { return value ? String(value).slice(0, 10) : ""; }

export function SettingsPanel({ open, dark, onDarkChange, onClose, onDataChanged, demoMode = false, demoExpiresAt = null, onDemoReset, onDemoLeave }: SettingsPanelProps) {
  const semesterTouched = useRef(false); const installPrompt = useInstallPrompt(); const [message, setMessage] = useState(""); const [storagePersisted, setStoragePersisted] = useState(false); const [pushStatus, setPushStatus] = useState<"unsupported" | "default" | "denied" | "granted" | "subscribed">("default"); const [pushBusy, setPushBusy] = useState(false); const [subscriptions, setSubscriptions] = useState<Subscription[]>([]); const [subscriptionName, setSubscriptionName] = useState(""); const [subscriptionUrl, setSubscriptionUrl] = useState(""); const [icsUrl, setIcsUrl] = useState(""); const [semesterStartDate, setSemesterStartDate] = useState(""); const [reminderSoundEnabled, setReminderSoundEnabled] = useState(true); const [tagName, setTagName] = useState("");
  useEffect(() => { if (!open) return; void navigator.storage?.persisted?.().then(setStoragePersisted).catch(() => setStoragePersisted(false)); }, [open]);
  useEffect(() => { if (!open) return; void refreshPushStatus(); }, [open]);
  useEffect(() => { if (!open) return; void api<{ subscriptions: Subscription[] }>("/api/v1/subscriptions").then((value) => setSubscriptions(value.subscriptions)).catch(() => undefined); void api<{ settings: { icsUrl: string; semesterStartDate: string | null; reminderSoundEnabled: boolean } }>("/api/v1/settings").then((value) => { setIcsUrl(value.settings.icsUrl); setReminderSoundEnabled(value.settings.reminderSoundEnabled); if (!semesterTouched.current) setSemesterStartDate(normalizeSemesterDate(value.settings.semesterStartDate)); }).catch(() => undefined); }, [open]);
  async function refreshPushStatus() {
    if (!("Notification" in window) || !("serviceWorker" in navigator) || !("PushManager" in window)) { setPushStatus("unsupported"); return; }
    if (Notification.permission === "denied") { setPushStatus("denied"); return; }
    try {
      const registration = await navigator.serviceWorker.ready;
      const subscription = await registration.pushManager.getSubscription();
      setPushStatus(subscription ? "subscribed" : Notification.permission === "granted" ? "granted" : "default");
    } catch {
      setPushStatus("default");
    }
  }
  async function enablePush() {
    setPushBusy(true);
    try {
      if (!("Notification" in window) || !("serviceWorker" in navigator) || !("PushManager" in window)) throw new Error("此浏览器不支持后台通知");
      const permission = Notification.permission === "default" ? await Notification.requestPermission() : Notification.permission;
      if (permission !== "granted") { setPushStatus("denied"); throw new Error("通知权限未授予，请在浏览器设置中允许通知"); }
      const publicKey = (await api<{ publicKey: string | null }>("/api/v1/reminders/vapid-public-key")).publicKey;
      if (!publicKey) throw new Error("服务器尚未配置 VAPID 密钥");
      const registration = await navigator.serviceWorker.ready;
      const subscription = (await registration.pushManager.getSubscription()) ?? await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: publicKey });
      await apiJson("/api/v1/reminders/push-subscriptions", "POST", subscription.toJSON());
      setPushStatus("subscribed");
      setMessage("后台提醒已启用，最小化后也可接收系统通知");
    } catch (error) {
      await refreshPushStatus();
      setMessage(error instanceof Error ? error.message : "启用失败");
    } finally {
      setPushBusy(false);
    }
  }
  async function testPushNotification() {
    setPushBusy(true);
    try {
      const result = await apiJson<{ sent: number }>("/api/v1/reminders/test-push", "POST", {});
      if (result.sent === 0) throw new Error("还没有已启用的设备，请先点击“开启后台提醒”");
      setMessage(`测试通知已发送到 ${result.sent} 个设备`);
    } catch (error) {
      setMessage(error instanceof Error ? error.message : "测试通知发送失败");
    } finally {
      setPushBusy(false);
    }
  }
  async function addPasskey() { const result = await authClient.passkey.addPasskey({ name: navigator.userAgent.includes("Mobile") ? "手机通行密钥" : "电脑通行密钥" }); setMessage(result.error ? result.error.message ?? "添加失败" : "通行密钥已添加"); }
  async function importFile(file: File) { const body = new FormData(); body.append("file", file); const result = await api<{ importedCount: number; skippedCount: number; errors: unknown[] }>("/api/v1/exchange/import", { method: "POST", body }); setMessage(`导入 ${result.importedCount} 条，跳过 ${result.skippedCount} 条，失败 ${result.errors.length} 条`); onDataChanged(); }
  async function addSubscription() { const value = await apiJson<{ subscription: Subscription }>("/api/v1/subscriptions", "POST", { name: subscriptionName, url: subscriptionUrl }); setSubscriptions((items) => [...items, value.subscription]); setSubscriptionName(""); setSubscriptionUrl(""); setMessage("订阅已添加，将在几分钟内刷新"); }
  async function refresh(id: string) { const value = await apiJson<{ imported: number }>(`/api/v1/subscriptions/${id}/refresh`, "POST"); setMessage(`已刷新 ${value.imported} 条日程`); onDataChanged(); }
  async function removeSubscription(id: string) { await apiJson(`/api/v1/subscriptions/${id}`, "DELETE"); setSubscriptions((items) => items.filter((item) => item.id !== id)); onDataChanged(); }
  async function saveSemester() { const valueToSave = normalizeSemesterDate(semesterStartDate); if (!valueToSave) { setMessage("请先选择学期开始日期，再点击保存"); return; } if (!window.confirm("修改学期开始日期会让所有单双周日程按新日期重新展开，确定继续吗？")) return; try { const value = await apiJson<{ settings: { semesterStartDate: string | null } }>("/api/v1/settings", "PATCH", { semesterStartDate: valueToSave }); const saved = normalizeSemesterDate(value.settings.semesterStartDate); semesterTouched.current = false; setSemesterStartDate(saved); setMessage(`学期开始日期已保存：${saved}`); onDataChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : "保存失败"); } }
  async function toggleReminderSound() { const next = !reminderSoundEnabled; setReminderSoundEnabled(next); try { await apiJson("/api/v1/settings", "PATCH", { reminderSoundEnabled: next }); onDataChanged(); if (next) void playReminderSound(); setMessage(next ? "提醒提示音已开启" : "提醒提示音已关闭"); } catch (error) { setReminderSoundEnabled(!next); setMessage(error instanceof Error ? error.message : "设置保存失败"); } }
  async function testReminderSound() { const played = await playReminderSound(); setMessage(played ? "声音测试成功" : "浏览器暂未允许播放声音，请先点击页面任意位置再试"); }
  async function clearSemester() { if (!window.confirm("确定清除学期开始日期吗？清除后单双周筛选将无法使用。")) return; try { await apiJson("/api/v1/settings", "PATCH", { semesterStartDate: null }); semesterTouched.current = false; setSemesterStartDate(""); setMessage("学期开始日期已清除"); onDataChanged(); } catch (error) { setMessage(error instanceof Error ? error.message : "清除失败"); } }
  async function createTag() { await apiJson("/api/v1/tags", "POST", { name: tagName, color: "#f97316" }); setTagName(""); setMessage("标签已创建"); onDataChanged(); }
  async function rotateIcs() { const value = await apiJson<{ token: string }>("/api/v1/settings/rotate-ics-token", "POST"); setIcsUrl(`${window.location.origin}/api/v1/ics/${value.token}`); }
  return <Dialog.Root open={open} onOpenChange={(next) => !next && onClose()}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-40 bg-stone-950/40 backdrop-blur-sm"/><Dialog.Content className="fixed inset-y-0 right-0 z-50 w-full max-w-lg overflow-y-auto border-l border-app bg-[var(--surface)] p-5 shadow-2xl">
    <div className="flex items-center justify-between"><div><Dialog.Title className="text-xl font-black">设置</Dialog.Title><Dialog.Description className="muted text-sm">通知、同步、数据与隐私</Dialog.Description></div><Dialog.Close className="grid size-10 place-items-center rounded-full hover-surface"><X size={20}/></Dialog.Close></div>
    {message && <p className="mt-4 rounded-xl bg-orange-50 p-3 text-sm text-orange-800 dark:bg-orange-950/50 dark:text-orange-100">{message}</p>}
    {demoMode && <section className="mt-6 rounded-2xl border border-orange-200 bg-orange-50 p-4 dark:border-orange-900 dark:bg-orange-950/40"><h2 className="font-black">体验空间</h2><p className="mt-1 text-sm text-orange-900 dark:text-orange-100">你的示例数据与其他访客隔离，24 小时后自动清理。</p>{demoExpiresAt && <p className="muted mt-1 text-xs">有效期至 {new Date(demoExpiresAt).toLocaleString("zh-CN")}</p>}<div className="mt-3 flex gap-2"><button onClick={onDemoReset} className="rounded-xl border border-orange-300 px-3 py-2 text-sm font-bold dark:border-orange-800">重置示例数据</button><button onClick={onDemoLeave} className="rounded-xl border border-red-300 px-3 py-2 text-sm font-bold text-danger dark:border-red-900">退出体验</button></div></section>}
    <section className="mt-6 space-y-3"><h2 className="font-black">安装应用</h2>{installPrompt.installed ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/40 dark:text-emerald-200">已安装，可从桌面图标独立打开</div> : <>{installPrompt.canInstall && <button onClick={() => void installPrompt.install()} className="flex w-full items-center gap-2 rounded-2xl border border-app p-4 font-bold"><Download size={18}/>安装到桌面</button>}{installPrompt.isIOS && <div className="rounded-2xl border border-app p-4 text-sm"><strong className="block">iPhone / iPad 安装方法</strong><span className="muted mt-1 block">在 Safari 中点击“分享”，再选择“添加到主屏幕”。</span></div>}{!installPrompt.canInstall && !installPrompt.isIOS && <p className="muted text-sm">可通过浏览器菜单中的“安装应用 / 添加到主屏幕”完成安装。</p>}</>}</section>
    <section className="mt-6 space-y-3"><h2 className="font-black">本机数据</h2><div className="flex items-center justify-between rounded-2xl border border-app p-4"><span className="flex items-center gap-2 font-bold"><HardDrive size={18}/>本地持久存储</span><span className="text-sm">{storagePersisted ? "已启用" : "由浏览器管理"}</span></div><button onClick={() => void requestPersistentStorage().then(setStoragePersisted)} className="w-full rounded-2xl border border-app p-3 text-sm font-bold">尝试启用持久存储</button><button onClick={async () => { if (!window.confirm("清除当前账号在本机的离线缓存？云端数据不会删除。")) return; await clearOfflineData(); window.location.reload(); }} className="flex w-full items-center justify-center gap-2 rounded-2xl border border-red-300 p-3 text-sm font-bold text-danger dark:border-red-900"><Trash2 size={16}/>清除当前账号本机数据</button></section>
    <section className="mt-6 space-y-3"><h2 className="font-black">外观与通知</h2><button onClick={() => onDarkChange(!dark)} className="flex w-full items-center justify-between rounded-2xl border border-app p-4"><span className="flex items-center gap-2 font-bold">{dark ? <Moon size={18}/> : <Sun size={18}/>}深色模式</span><span>{dark ? "已开启" : "已关闭"}</span></button><button onClick={() => void toggleReminderSound()} className="flex w-full items-center justify-between rounded-2xl border border-app p-4"><span className="flex items-center gap-2 font-bold"><Bell size={18}/>提醒提示音</span><span>{reminderSoundEnabled ? "已开启" : "已关闭"}</span></button><button onClick={() => void testReminderSound()} className="flex w-full items-center gap-2 rounded-2xl border border-app p-4 font-bold"><Bell size={18}/>测试提示音</button>{!demoMode && <><div className="rounded-2xl border border-app p-4 text-sm"><div className="flex items-center justify-between"><strong>后台提醒状态</strong><span>{pushStatus === "subscribed" ? "已启用" : pushStatus === "denied" ? "权限被拒绝" : pushStatus === "unsupported" ? "浏览器不支持" : "未启用"}</span></div><p className="muted mt-1 text-xs">{pushStatus === "denied" ? "请在浏览器或系统设置中允许本站通知后重试。" : "启用后，PWA 最小化时仍能收到系统提醒。"}</p></div><button disabled={pushBusy} onClick={() => void enablePush()} className="flex w-full items-center gap-2 rounded-2xl border border-app p-4 font-bold disabled:opacity-50"><Bell size={18}/>{pushStatus === "subscribed" ? "重新同步后台提醒" : "开启后台提醒"}</button><button disabled={pushBusy || pushStatus !== "subscribed"} onClick={() => void testPushNotification()} className="flex w-full items-center gap-2 rounded-2xl border border-app p-4 font-bold disabled:opacity-50"><Bell size={18}/>发送测试通知</button><button onClick={() => void addPasskey()} className="flex w-full items-center gap-2 rounded-2xl border border-app p-4 font-bold"><Fingerprint size={18}/>添加通行密钥</button></>}</section>
    <section className="mt-7 space-y-3"><h2 className="font-black">学期设置</h2><p className="muted text-sm">用于单双周计算：填写学期第 1 周的周一。</p><div className="flex gap-2"><input type="date" aria-label="学期第 1 周周一" value={normalizeSemesterDate(semesterStartDate)} onChange={(event) => { semesterTouched.current = true; setSemesterStartDate(event.target.value); }} className="min-w-0 flex-1 rounded-xl border border-app bg-[var(--input-bg)] px-3 py-2.5"/><button onClick={() => void saveSemester()} className="rounded-xl bg-orange-500 px-4 font-bold text-stone-950">保存</button>{semesterStartDate && <button onClick={() => void clearSemester()} className="rounded-xl border border-app px-3 text-sm">清除</button>}</div>{semesterStartDate && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800 dark:bg-emerald-950/40 dark:text-emerald-200">已保存：{normalizeSemesterDate(semesterStartDate)}</p>}<p className="muted text-xs">设置后，请在每周重复日程中选择“单周”或“双周”才会生效；未选择时仍是每周重复。</p><p className="muted text-xs">修改后，所有单双周日程按新日期重新展开，不会改动原始日程时间。</p></section>
    <section className="mt-7 space-y-3"><h2 className="font-black">数据导入导出</h2><div className="grid grid-cols-3 gap-2">{[["json","JSON"],["csv","CSV"],["ics","ICS"]].map(([format,label]) => <a key={format} href={`/api/v1/exchange/export?format=${format}`} className="flex items-center justify-center gap-2 rounded-xl border border-app p-3 text-sm font-bold"><CloudDownload size={16}/>{label}</a>)}</div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed border-app p-4 text-sm font-bold"><CloudUpload size={18}/>导入 JSON / CSV / ICS<input className="hidden" type="file" accept=".json,.csv,.ics,text/calendar" onChange={(event) => { const file = event.target.files?.[0]; if (file) void importFile(file); }}/></label></section>
    <section className="mt-7 space-y-3"><h2 className="font-black">标签</h2><div className="flex gap-2"><input value={tagName} onChange={(event) => setTagName(event.target.value)} placeholder="新标签名称" className="min-w-0 flex-1 rounded-xl border border-app bg-transparent px-3"/><button disabled={!tagName} onClick={() => void createTag()} className="rounded-xl bg-orange-500 px-3 text-stone-950 disabled:opacity-50"><Plus size={18}/></button></div></section>
    {!demoMode && (    <section className="mt-7 space-y-3"><h2 className="flex items-center gap-2 font-black"><Rss size={18}/>外部日历订阅</h2><input value={subscriptionName} onChange={(event) => setSubscriptionName(event.target.value)} placeholder="日历名称" className="w-full rounded-xl border border-app bg-transparent px-3 py-2.5"/><input value={subscriptionUrl} onChange={(event) => setSubscriptionUrl(event.target.value)} placeholder="ICS 订阅地址" className="w-full rounded-xl border border-app bg-transparent px-3 py-2.5"/><button disabled={!subscriptionName || !subscriptionUrl} onClick={() => void addSubscription()} className="w-full rounded-xl bg-stone-900 px-4 py-3 font-bold text-white disabled:opacity-50 dark:bg-white dark:text-stone-900">添加只读订阅</button>{subscriptions.map((subscription) => <div key={subscription.id} className="rounded-2xl border border-app p-3"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate font-bold">{subscription.name}</p><p className="muted truncate text-xs">{subscription.url}</p></div><div className="flex gap-1"><button onClick={() => void refresh(subscription.id)} className="rounded-lg border border-app px-2 py-1 text-xs">刷新</button><button onClick={() => void removeSubscription(subscription.id)} className="rounded-lg p-2 text-danger"><Trash2 size={16}/></button></div></div>{subscription.lastError && <p className="mt-2 text-xs text-danger">{subscription.lastError}</p>}</div>)}</section>)}
    {!demoMode && (    <section className="mt-7 space-y-3"><h2 className="font-black">只读订阅源</h2><div className="flex gap-2"><input readOnly value={icsUrl} className="min-w-0 flex-1 rounded-xl border border-app bg-transparent px-3 text-xs"/><button onClick={() => void navigator.clipboard.writeText(icsUrl)} className="rounded-xl border border-app px-3 text-sm">复制</button></div><button onClick={() => void rotateIcs()} className="text-sm font-bold text-danger">轮换订阅令牌</button></section>)}
    <button onClick={async () => { if (demoMode) { onDemoLeave?.(); return; } clearLastSession(); await authClient.signOut(); window.location.reload(); }} className="mt-8 w-full rounded-xl border border-red-300 dark:border-red-900 p-3 font-bold text-danger">{demoMode ? "退出体验" : "退出登录"}</button>
  </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
