import { useEffect, useLayoutEffect, useRef, useState } from "react";
import { CheckCircle2, Circle, Clock3, LoaderCircle, Plus, RefreshCcw, RotateCcw, X } from "lucide-react";
import { isTaskKind, type ExpandedItem, type Priority, type Tag } from "@calendar/domain";
import { api, apiJson } from "../lib/api";
import { readableTextColor } from "../lib/colors";
import { PRIORITY_META, PRIORITY_ORDER, PRIORITY_RANK } from "../lib/priority";

type ResolutionOutcome = "completed" | "partial" | "postponed" | "cancelled";
interface Suggestion { startAt: string | null; endAt: string | null; dueAt: string | null; label: string; }
interface ReviewEntry { deliveryId: string; itemId: string; occurrenceKey: string; title: string; scheduledAt: string; status: string; autoRollover: boolean; }
interface TasksPanelProps { items: ExpandedItem[]; tags: Tag[]; pendingTaskIds: ReadonlySet<string>; onOpen: (item: ExpandedItem) => void; onToggle: (item: ExpandedItem) => Promise<void>; onResolve: (item: ExpandedItem, outcome: ResolutionOutcome, occurrenceKey?: string | null, suggestion?: Suggestion) => Promise<void>; onRefresh?: () => void; onCreate: () => void; }
const FILTERS: Array<Priority | "all"> = ["all", ...PRIORITY_ORDER];
type ScheduledSort = "time_asc" | "time_desc" | "priority" | "updated";
type StatusFilter = "all" | "active" | "partial" | "completed";

function sortTasks(left: ExpandedItem, right: ExpandedItem, newestFirst = false) {
  const completedOrder = Number(left.status === "completed") - Number(right.status === "completed");
  if (completedOrder !== 0) return completedOrder;
  const priorityOrder = PRIORITY_RANK[right.priority] - PRIORITY_RANK[left.priority];
  if (priorityOrder !== 0) return priorityOrder;
  if (newestFirst) return right.updatedAt.localeCompare(left.updatedAt);
  return (left.dueAt ?? left.startAt ?? "9999").localeCompare(right.dueAt ?? right.startAt ?? "9999");
}
function sortScheduledTasks(tasks: ExpandedItem[], sort: ScheduledSort) {
  return [...tasks].sort((left, right) => {
    const completedOrder = Number(left.status === "completed") - Number(right.status === "completed");
    if (completedOrder !== 0) return completedOrder;
    if (sort === "priority") return PRIORITY_RANK[right.priority] - PRIORITY_RANK[left.priority];
    if (sort === "updated") return right.updatedAt.localeCompare(left.updatedAt);
    const leftTime = new Date(left.startAt ?? left.dueAt ?? 0).getTime();
    const rightTime = new Date(right.startAt ?? right.dueAt ?? 0).getTime();
    return sort === "time_desc" ? rightTime - leftTime : leftTime - rightTime;
  });
}
function useTaskFlipAnimation() {
  const positions = useRef<Map<string, DOMRect>>(new Map()); const animations = useRef<Map<string, Animation>>(new Map());
  useLayoutEffect(() => {
    const reduceMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    const elements = Array.from(document.querySelectorAll<HTMLElement>("[data-task-card-id]")).filter((element) => element.offsetParent !== null);
    const next = new Map<string, DOMRect>();
    for (const element of elements) {
      const id = element.dataset.taskCardId; if (!id) continue;
      const previousAnimation = animations.current.get(id); if (previousAnimation && previousAnimation.playState !== "finished") previousAnimation.cancel();
      const rect = element.getBoundingClientRect(); const previous = positions.current.get(id); next.set(id, rect);
      if (!reduceMotion && previous) { const dx = previous.left - rect.left; const dy = previous.top - rect.top; if (Math.abs(dx) > 1 || Math.abs(dy) > 1) { const animation = element.animate([{ transform: `translate(${dx}px, ${dy}px)` }, { transform: "translate(0, 0)" }], { duration: 360, delay: 150, easing: "cubic-bezier(0.2, 0.8, 0.2, 1)", fill: "both" }); animations.current.set(id, animation); } }
    }
    positions.current = next;
  });
}function TaskCard({ task, items, tags, pending, onOpen, onToggle, onRollover }: { task: ExpandedItem; items: ExpandedItem[]; tags: Tag[]; pending: boolean; onOpen: (item: ExpandedItem) => void; onToggle: (item: ExpandedItem) => Promise<void>; onRollover: (item: ExpandedItem) => void }) {
  const cardRef = useRef<HTMLElement>(null); const completed = task.status === "completed"; const previousCompleted = useRef(completed);
  useEffect(() => { if (previousCompleted.current === completed || !cardRef.current || window.matchMedia("(prefers-reduced-motion: reduce)").matches) { previousCompleted.current = completed; return; } cardRef.current.animate([{ transform: "scale(1)", filter: "brightness(1)", boxShadow: "0 0 0 rgba(249,115,22,0)" }, { transform: "scale(1.035)", filter: "brightness(1.12)", boxShadow: "0 0 0 6px rgba(249,115,22,0.14)", offset: 0.45 }, { transform: "scale(1)", filter: "brightness(1)", boxShadow: "0 0 0 rgba(249,115,22,0)" }], { duration: 220, easing: "ease-out" }); previousCompleted.current = completed; }, [completed]);
  const priority = PRIORITY_META[task.priority]; const children = items.filter((item) => item.parentId === task.id); const taskTags = tags.filter((tag) => task.tagIds.includes(tag.id)); const partial = task.status === "partial";
  return <article ref={cardRef} data-task-card-id={task.id} className={`rounded-2xl border border-l-4 border-app bg-[var(--panel)] p-4 transition ${priority.borderClass} ${completed ? "surface-muted" : partial ? "bg-amber-50/70 dark:bg-amber-950/20" : "hover:-translate-y-0.5 hover:shadow-lg"}`}>
    <div className="flex gap-3"><button disabled={pending} aria-busy={pending} onClick={() => void onToggle(task)} className={`mt-0.5 grid size-8 shrink-0 place-items-center rounded-full border ${completed ? "border-emerald-500 bg-emerald-500 text-white" : partial ? "border-amber-500 bg-amber-400 text-stone-950" : "border-app text-orange-500"}`} title={completed ? "取消完成" : "标记为完成"}>{pending ? <LoaderCircle className="animate-spin" size={17}/> : completed ? <CheckCircle2 size={18}/> : partial ? <Clock3 size={17}/> : <Circle size={18}/>}</button>
      <button onClick={() => onOpen(task)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><span className={`font-bold ${completed ? "line-through opacity-60" : ""}`}>{task.title}</span>{task.kind === "both" && <span className="rounded-full bg-orange-100 px-2 py-0.5 text-[10px] font-black text-orange-700 dark:bg-orange-950 dark:text-orange-200">日历+任务</span>}{partial && <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[10px] font-black text-amber-800 dark:bg-amber-950 dark:text-amber-200">部分完成</span>}{task.priority !== "none" && <span className={`rounded-full px-2 py-0.5 text-[10px] font-black ${priority.badgeClass}`}>{priority.label}优先级</span>}{task.autoRollover && <span className="rounded-full border border-app px-2 py-0.5 text-[10px] font-bold muted">可顺延</span>}</div><div className="muted mt-1 flex flex-wrap items-center gap-2 text-xs">{(task.startAt || task.dueAt) && <span><Clock3 className="mr-1 inline" size={12}/>{new Date(task.startAt ?? task.dueAt ?? "").toLocaleString("zh-CN")}</span>}{task.dueAt && task.startAt && <span>截止 {new Date(task.dueAt).toLocaleString("zh-CN")}</span>}{taskTags.map((tag) => <span key={tag.id} className="rounded-full px-2 py-1 font-bold" style={{ background: tag.color, color: readableTextColor(tag.color) }}>{tag.name}</span>)}</div>{children.length > 0 && <p className="muted mt-3 text-xs">子任务 {children.filter((child) => child.status === "completed").length}/{children.length}</p>}</button>
      {task.autoRollover && task.status !== "completed" && task.status !== "cancelled" && <button onClick={() => onRollover(task)} className="mt-1 self-start rounded-lg border border-orange-300 px-2 py-1 text-xs font-bold text-orange-700 dark:border-orange-800 dark:text-orange-200" title="顺延建议"><RotateCcw size={13}/></button>}
    </div>
  </article>;
}export function TasksPanel({ items, tags, pendingTaskIds, onOpen, onToggle, onResolve, onRefresh, onCreate }: TasksPanelProps) {
  useTaskFlipAnimation();
  const [priorityFilter, setPriorityFilter] = useState<Priority | "all">("all"); const [scheduledSort, setScheduledSort] = useState<ScheduledSort>("time_asc"); const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [rolloverItem, setRolloverItem] = useState<ExpandedItem | null>(null); const [suggestions, setSuggestions] = useState<Suggestion[]>([]); const [rolloverBusy, setRolloverBusy] = useState(false);
  const [reviews, setReviews] = useState<ReviewEntry[]>([]); const [selectedReviews, setSelectedReviews] = useState<Set<string>>(new Set()); const [reviewBusy, setReviewBusy] = useState(false); const [reviewMessage, setReviewMessage] = useState("");
  async function loadReviews() { try { setReviews((await api<{ reviews: ReviewEntry[] }>("/api/v1/reviews")).reviews); } catch { /* offline */ } }
  useEffect(() => { void loadReviews(); }, [items]);
  const allTasks = items.filter((item) => isTaskKind(item.kind) && item.status !== "deleted" && !item.parentId);
  const tasks = priorityFilter === "all" ? allTasks : allTasks.filter((task) => task.priority === priorityFilter);
  const unscheduled = tasks.filter((task) => !task.startAt && !task.endAt && !task.dueAt).sort((left, right) => sortTasks(left, right, true));
  const matchesStatus = (task: ExpandedItem) => statusFilter === "all" || (statusFilter === "active" ? task.status === "active" || task.status === "partial" : task.status === statusFilter);
  const scheduled = sortScheduledTasks(tasks.filter((task) => task.startAt || task.endAt || task.dueAt).filter(matchesStatus), scheduledSort);
  async function openRollover(item: ExpandedItem) { setRolloverItem(item); setRolloverBusy(true); try { const response = await api<{ suggestions: Suggestion[] }>(`/api/v1/items/${item.id}/rollover-suggestions`); setSuggestions(response.suggestions); } catch { setSuggestions([]); } finally { setRolloverBusy(false); } }
  async function confirmRollover(suggestion: Suggestion) { if (!rolloverItem) return; setRolloverBusy(true); try { await onResolve(rolloverItem, "postponed", null, suggestion); setRolloverItem(null); setSuggestions([]); } finally { setRolloverBusy(false); } }
  async function batch(outcome: Exclude<ResolutionOutcome, "postponed">) { const chosen = reviews.filter((review) => selectedReviews.has(review.deliveryId)); if (chosen.length === 0) return; setReviewBusy(true); try { await apiJson("/api/v1/reviews/batch", "POST", { entries: chosen.map((review) => ({ itemId: review.itemId, occurrenceKey: review.occurrenceKey === review.itemId ? null : review.occurrenceKey, outcome })) }); setSelectedReviews(new Set()); setReviewMessage("批量处理已提交"); await loadReviews(); onRefresh?.(); } catch { setReviewMessage("批量处理失败，请重试"); } finally { setReviewBusy(false); } }
  async function batchPostpone() { const chosen = reviews.filter((review) => selectedReviews.has(review.deliveryId)); if (chosen.length === 0) return; setReviewBusy(true); try { const entries = []; for (const review of chosen) { const response = await api<{ suggestions: Suggestion[] }>(`/api/v1/items/${review.itemId}/rollover-suggestions?occurrenceKey=${encodeURIComponent(review.occurrenceKey)}`); const suggestion = response.suggestions[0]; entries.push({ itemId: review.itemId, occurrenceKey: review.occurrenceKey === review.itemId ? null : review.occurrenceKey, outcome: suggestion ? "postponed" : "partial", ...(suggestion ?? {}) }); } await apiJson("/api/v1/reviews/batch", "POST", { entries }); setSelectedReviews(new Set()); setReviewMessage("批量顺延建议已应用"); await loadReviews(); onRefresh?.(); } catch { setReviewMessage("批量顺延失败，请重试"); } finally { setReviewBusy(false); } }  return <section className="mx-auto max-w-3xl p-4 pb-28 md:p-7">
    <div className="mb-5 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-orange-500">Tasks</p><h1 className="text-3xl font-black">任务</h1><p className="muted mt-1">待办、已安排和待复盘集中处理</p></div><button onClick={onCreate} className="flex min-h-11 items-center gap-2 rounded-xl bg-orange-500 px-4 font-bold text-stone-950"><Plus size={18}/>新建任务</button></div>
    {reviews.length > 0 && <section className="mb-6 rounded-3xl border border-amber-200 bg-amber-50/60 p-4 dark:border-amber-900 dark:bg-amber-950/20"><div className="flex items-center justify-between gap-2"><div><h2 className="font-black">待复盘</h2><p className="muted text-xs">{reviews.length} 条错过或待确认</p></div><button onClick={() => void loadReviews()} className="rounded-lg border border-app p-2" title="刷新"><RefreshCcw size={15}/></button></div><div className="mt-3 max-h-52 space-y-2 overflow-y-auto">{reviews.map((review) => <label key={review.deliveryId} className="flex items-center gap-3 rounded-xl border border-app bg-[var(--panel)] p-3 text-sm"><input type="checkbox" checked={selectedReviews.has(review.deliveryId)} onChange={(event) => setSelectedReviews((current) => { const next = new Set(current); if (event.target.checked) next.add(review.deliveryId); else next.delete(review.deliveryId); return next; })}/><span className="min-w-0 flex-1"><strong className="block truncate">{review.title}</strong><span className="muted text-xs">{new Date(review.scheduledAt).toLocaleString("zh-CN")}</span></span>{review.autoRollover && <span className="text-xs text-orange-600">可顺延</span>}</label>)}</div><div className="mt-3 flex flex-wrap gap-2"><button disabled={reviewBusy || selectedReviews.size === 0} onClick={() => void batch("completed")} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-50">批量完成</button><button disabled={reviewBusy || selectedReviews.size === 0} onClick={() => void batch("partial")} className="rounded-lg bg-amber-500 px-3 py-2 text-xs font-bold text-stone-950 disabled:opacity-50">批量部分完成</button><button disabled={reviewBusy || selectedReviews.size === 0} onClick={() => void batchPostpone()} className="rounded-lg border border-orange-400 px-3 py-2 text-xs font-bold text-orange-700 disabled:opacity-50 dark:text-orange-200">批量顺延</button><button disabled={reviewBusy || selectedReviews.size === 0} onClick={() => void batch("cancelled")} className="rounded-lg border border-red-300 px-3 py-2 text-xs font-bold text-danger disabled:opacity-50 dark:border-red-900">批量取消本次</button>{reviewMessage && <span className="muted self-center text-xs">{reviewMessage}</span>}</div></section>}
    <div className="mb-5 flex gap-2 overflow-x-auto pb-1">{FILTERS.map((value) => { const meta = value === "all" ? null : PRIORITY_META[value]; const active = priorityFilter === value; return <button key={value} onClick={() => setPriorityFilter(value)} className={`flex shrink-0 items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-bold ${active ? "border-stone-900 bg-stone-900 text-white dark:border-white dark:bg-white dark:text-stone-900" : "border-app surface-elevated"}`}>{meta && <span className={`size-2 rounded-full ${meta.dotClass}`}/>}<span>{meta?.label ?? "全部"}</span></button>; })}</div>    {tasks.length === 0 ? <div className="rounded-3xl border border-dashed border-app p-12 text-center"><CheckCircle2 className="mx-auto mb-3 text-orange-500"/><p className="font-bold">没有符合条件的任务</p><p className="muted text-sm">调整筛选或点击“新建任务”</p></div> : <div className="space-y-7"><section><div className="mb-3 flex items-center justify-between"><h2 className="font-black">待安排</h2><span className="muted text-xs">{unscheduled.length} 项</span></div><div className="space-y-3">{unscheduled.length === 0 ? <p className="rounded-2xl border border-dashed border-app p-5 text-sm muted">没有待安排任务</p> : unscheduled.map((task) => <TaskCard key={task.id} task={task} items={items} tags={tags} pending={pendingTaskIds.has(task.id)} onOpen={onOpen} onToggle={onToggle} onRollover={(item) => void openRollover(item)}/>)}</div></section><section><div className="mb-3 flex flex-wrap items-center gap-2"><h2 className="font-black">已安排</h2><select aria-label="已安排排序" value={scheduledSort} onChange={(event) => setScheduledSort(event.target.value as ScheduledSort)} className="ml-auto rounded-lg border border-app bg-[var(--input-bg)] px-2 py-1.5 text-xs font-bold"><option value="time_asc">时间从早到晚</option><option value="time_desc">时间从晚到早</option><option value="priority">优先级从高到低</option><option value="updated">最近更新</option></select><select aria-label="完成状态" value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as StatusFilter)} className="rounded-lg border border-app bg-[var(--input-bg)] px-2 py-1.5 text-xs font-bold"><option value="all">全部状态</option><option value="active">未完成</option><option value="partial">部分完成</option><option value="completed">已完成</option></select><span className="muted text-xs">{scheduled.length} 项</span></div><div className="space-y-3">{scheduled.length === 0 ? <p className="rounded-2xl border border-dashed border-app p-5 text-sm muted">暂无已安排任务</p> : scheduled.map((task) => <TaskCard key={task.id} task={task} items={items} tags={tags} pending={pendingTaskIds.has(task.id)} onOpen={onOpen} onToggle={onToggle} onRollover={(item) => void openRollover(item)}/>)}</div></section></div>}
    {rolloverItem && <div className="fixed inset-0 z-[70] grid place-items-center bg-stone-950/40 p-4" onClick={() => setRolloverItem(null)}><div className="w-full max-w-md rounded-3xl border border-app bg-[var(--surface)] p-5 shadow-2xl" onClick={(event) => event.stopPropagation()}><div className="flex items-center justify-between"><h3 className="font-black">顺延建议</h3><button onClick={() => setRolloverItem(null)} className="rounded-full p-2 hover-surface"><X size={16}/></button></div><p className="muted mt-1 text-sm">{rolloverItem.title}</p>{rolloverBusy ? <p className="mt-5 text-sm muted">正在查找可用时间…</p> : suggestions.length === 0 ? <p className="mt-5 rounded-xl border border-dashed border-app p-4 text-sm muted">未来 7 天暂无可用时间</p> : <div className="mt-4 space-y-2">{suggestions.map((suggestion) => <button key={`${suggestion.startAt}-${suggestion.dueAt}`} onClick={() => void confirmRollover(suggestion)} className="w-full rounded-xl border border-app p-3 text-left hover-surface"><span className="font-bold">{suggestion.label}</span><span className="muted ml-2">{new Date(suggestion.startAt ?? suggestion.dueAt ?? "").toLocaleString("zh-CN")}</span></button>)}</div>}</div></div>}
  </section>;
}